PLANNER: FISS+ # the name of the planner to be used, can be: FOP, FOP+, FISS, FISS+
N_W_SAMPLE: 5 # number of lateral samples
N_S_SAMPLE: 5 # number of longitudinal samples
N_T_SAMPLE: 5 # number of time samples
SAVE_GIF: True # Save the animation as a .gif file